import type { Meta, StoryObj } from '@storybook/react-vite'
import { MoonWitnessProvider } from './MoonWitnessProvider'
import { EvidenceRules, ProvenanceRail, SourceSeal, WitnessThread } from './EvidenceFlow'
import { EvidenceSpine, ObservationShard, ReliabilityPrism, SignalBeacon } from './Observatory'
import { InstrumentGrid, InstrumentHeader } from './PagePrimitives'

const meta = { title: 'MoonWitness/Evidence System', parameters: { layout: 'fullscreen' } } satisfies Meta
export default meta
type Story = StoryObj<typeof meta>

export const ProvenanceSystem: Story = { render: () => <MoonWitnessProvider theme="myth-fade"><div className="mw-page-stage"><InstrumentHeader code="EVIDENCE / PROVENANCE" title="Evidence Cathedral" subtitle="Evidence UI preserves source identity, claim scope, corroboration state, review state and archive provenance." status={<SignalBeacon tone="success" label="AUDITABLE"/>}/><div className="mw-page-stage__body"><WitnessThread steps={[{id:'s',label:'SOURCE',detail:'publisher / URL',state:'complete',tone:'success'},{id:'c',label:'CLAIM',detail:'bounded statement',state:'complete',tone:'active'},{id:'x',label:'CORROBORATE',detail:'cross-source',state:'complete',tone:'success'},{id:'r',label:'REVIEW',detail:'analysis',state:'active',tone:'warning'},{id:'a',label:'ARCHIVE',detail:'ledger'}]}/><InstrumentGrid><div className="span-5 mw-page-surface"><h2>PROVENANCE RAIL</h2><ProvenanceRail items={[{id:'SRC-001',type:'OFFICIAL',title:'Primary reference',meta:'publisher identified',verified:true,tone:'success'},{id:'SRC-002',type:'MEDIA',title:'Observation evidence',meta:'claim scoped',verified:true,tone:'active'},{id:'SRC-003',type:'ARCHIVE',title:'Historical context',meta:'supporting only',verified:false,tone:'warning'}]}/></div><div className="span-4"><EvidenceSpine steps={[{label:'INGEST',detail:'source captured',state:'complete'},{label:'NORMALIZE',detail:'metadata',state:'complete'},{label:'VERIFY',detail:'cross-check',state:'active'},{label:'ARCHIVE',detail:'pending'}]}/></div><div className="span-3" style={{display:'grid',gap:12}}><SourceSeal type="SOURCE CLASS" label="OFFICIAL" score="92 / 100" tone="success"/><ReliabilityPrism score={92}/><EvidenceRules rows={[{label:'Source ≠ claim',value:'SEPARATE',tone:'success'},{label:'Proximity ≠ proof',value:'ENFORCED',tone:'warning'},{label:'Scope',value:'BOUNDED'}]}/></div><div className="span-6"><ObservationShard eyebrow="SOURCE OBJECT" title="Observation Shard" tone="active">High-value evidence can use asymmetric shards rather than repeating generic cards.</ObservationShard></div><div className="span-6"><ObservationShard eyebrow="ARCHIVE OBJECT" title="Immutable Provenance" tone="success">The presentation layer never invents provenance or upgrades a source beyond repository evidence.</ObservationShard></div></InstrumentGrid></div></div></MoonWitnessProvider> }
