import type { Meta, StoryObj } from '@storybook/react-vite'
import { MoonWitnessProvider } from './MoonWitnessProvider'
import { CausalityGuardrail, EvidenceSpine, MapRift, MissionRail, ObservationShard, OrbitalCore, ReliabilityPrism, SignalBeacon, TemporalOrrery } from './Observatory'
import { ArchiveGate, ChronologyTrack, InspectorDock, InstrumentHeader, MetricRail, RevelationLens } from './PagePrimitives'
import { CausalityLattice, SignalWave, StateVector, TruthAperture } from './DataVizPrimitives'
import { ProvenanceRail, SourceSeal, WitnessThread } from './EvidenceFlow'
import { ActionRail, EmptySignal, InstrumentButton, LoadingOrbit, SegmentedRail, StatusMatrix } from './InteractionPrimitives'

const meta = { title:'MoonWitness/Component Families', parameters:{layout:'fullscreen'} } satisfies Meta
export default meta
type Story = StoryObj<typeof meta>
const canvas=(title:string,subtitle:string,children:React.ReactNode,theme:'myth-fade'|'cyan'|'amber'|'emerald'|'violet'='myth-fade')=><MoonWitnessProvider theme={theme}><div className="mw-page-stage"><InstrumentHeader code="COMPONENT FAMILY" title={title} subtitle={subtitle}/><div className="mw-page-stage__body">{children}</div></div></MoonWitnessProvider>

export const Navigation: Story = { render:()=>canvas('Navigation Instruments','Four canonical navigation surfaces. Consumers compose these; they do not fork them.',<div style={{display:'grid',gridTemplateColumns:'280px 1fr',gap:18}}><MissionRail activeId="evidence" items={[{id:'observe',label:'Observe'},{id:'evidence',label:'Evidence'},{id:'correlate',label:'Correlate'},{id:'map',label:'Map'},{id:'archive',label:'Archive'}]}/><div style={{display:'grid',gap:18,alignContent:'start'}}><ArchiveGate/><SegmentedRail value="review" items={[{id:'all',label:'All'},{id:'review',label:'Review',count:'12'},{id:'verified',label:'Verified',count:'15'}]}/><ActionRail actions={[{id:'observe',label:'Observe',active:true,tone:'active'},{id:'verify',label:'Verify',tone:'success'},{id:'review',label:'Review',tone:'warning'},{id:'archive',label:'Archive'}]}/></div></div>) }

export const Evidence: Story = { render:()=>canvas('Evidence Instruments','Four source/provenance primitives with explicit audit semantics.',<div style={{display:'grid',gridTemplateColumns:'1fr 1.2fr',gap:18}}><EvidenceSpine steps={[{label:'SOURCE',detail:'identified',state:'complete'},{label:'CLAIM',detail:'bounded',state:'complete'},{label:'MATCH',detail:'cross-check',state:'active'},{label:'REVIEW',detail:'pending'}]}/><div style={{display:'grid',gap:16}}><WitnessThread steps={[{id:'1',label:'SOURCE',state:'complete',tone:'success'},{id:'2',label:'CLAIM',state:'complete'},{id:'3',label:'REVIEW',state:'active',tone:'active'}]}/><ProvenanceRail items={[{id:'SRC-01',type:'OFFICIAL',title:'Primary source',meta:'verified',tone:'success',verified:true},{id:'SRC-02',type:'CONTEXT',title:'Observation record',meta:'linked',tone:'active',verified:true}]}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><SourceSeal type="SOURCE" label="VERIFIED" score="92/100" tone="success"/><ReliabilityPrism score={92}/></div></div></div>,'emerald') }

export const DataVisualization: Story = { render:()=>canvas('Signature Data Visualization','No generic dashboard identity: aperture, lattice, signal and vector are semantic instruments.',<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:18}}><TruthAperture score={90} label="MYTHOS ACTIVITY" detail="August 2026" tone="warning"/><CausalityLattice nodes={[{id:'a',x:16,y:35,label:'OBS',value:'17',tone:'active'},{id:'b',x:48,y:66,label:'ΔT',value:'time'},{id:'c',x:72,y:38,label:'REVIEW',value:'0–15',tone:'success'}]} edges={[{from:'a',to:'b',strength:.7},{from:'b',to:'c',strength:.4,dashed:true}]}/><SignalWave values={[2,5,3,8,4,9,6,7]} label="SIGNAL WAVE" detail="bounded series"/><StateVector items={[{label:'Evidence',value:82,tone:'success'},{label:'Proximity',value:58,tone:'warning'},{label:'Causal proof',value:15,tone:'success'}]}/></div>,'amber') }

export const GeoAndTime: Story = { render:()=>canvas('Geo + Temporal Instruments','Four surfaces for location, chronology, temporal windows and causality discipline.',<div style={{display:'grid',gap:18}}><MapRift title="GEO OBSERVATORY" points={[{id:'1',x:22,y:40,tone:'active'},{id:'2',x:54,y:62,tone:'warning'},{id:'3',x:78,y:36,tone:'danger'}]}/><ChronologyTrack points={[{id:'1',label:'OBSERVE',detail:'source'},{id:'2',label:'MEASURE',detail:'ΔT / km',tone:'active'},{id:'3',label:'REVIEW',detail:'causality',tone:'warning',active:true},{id:'4',label:'ARCHIVE',detail:'bounded',tone:'success'}]}/><TemporalOrrery activeIndex={3} points={['T-3','T-2','T-1','T0','T+1','T+2','T+3'].map(label=>({label}))}/><CausalityGuardrail/></div>,'cyan') }

export const FeedbackStates: Story = { render:()=>canvas('Feedback + System States','Four state families for actions, loading, empty and semantic status.',<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:18}}><div className="mw-page-surface"><h2>ACTIONS</h2><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><InstrumentButton tone="active">Primary</InstrumentButton><InstrumentButton tone="success" variant="secondary">Verified</InstrumentButton><InstrumentButton tone="warning" variant="secondary">Review</InstrumentButton><InstrumentButton disabled>Disabled</InstrumentButton></div></div><div className="mw-page-surface"><LoadingOrbit/></div><div className="mw-page-surface"><EmptySignal detail="No records in the selected window."/></div><StatusMatrix items={[{label:'ACTIVE',value:'FOCUS',tone:'active'},{label:'SUCCESS',value:'VERIFIED',tone:'success'},{label:'WARNING',value:'REVIEW',tone:'warning'},{label:'ERROR',value:'BLOCKED',tone:'danger'}]}/></div>,'violet') }

export const ContentAndLens: Story = { render:()=>canvas('Content + Revelation','Four content surfaces for bounded narrative, source confidence, portals and status.',<div style={{display:'grid',gap:18}}><RevelationLens items={[{key:'Q',name:"Al-Qur'an",tone:'success'},{key:'I',name:'Injil / Gospel',tone:'active'},{key:'T',name:'Taurat / Torah',tone:'warning'},{key:'Z',name:'Zabur / Psalms'}]}/><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:18}}><ObservationShard eyebrow="OBSERVATION" title="Bounded narrative" tone="active">Evidence-backed content surface with no automatic causal carry-over.</ObservationShard><ReliabilityPrism score={92}/><SignalBeacon tone="success" label="SOURCE / VERIFIED"/></div></div>,'emerald') }
